### ISSUE TITLE
Feature request: add *count* to relationship fields?

### ISSUE THREAD

**Issue by Vernal** [eliot-akira/custom-content-shortcode#2]
Hey There,

I'm not sure if you're looking for feature requests here, but I've got one! It would be to add count/start to acf related fields. 

Otherwise thanks for the great plugin and cheers!

Jason

**Comment by eliot-akira** [comment]
Hi Jason,

Sure, I added *start* and *count* parameters to ACF related fields.

It's been quite a while since I've actively worked on the plugin, so I don't have a good testing setup yet. Once I confirm that the new feature is working as expected, I'll push a new version to production/WP plugin repo.

There's a backlog of issues and feature requests on the plugin directory, and I'm hoping that I'll be able to manage them better on GitHub.

Thanks for the kind words!

**Comment by Vernal** [comment]
Wow! Thanks, Eliot. I just put it through some good testing and it seems to work just fine. Let me know if there is anything in particular I should poke at. Many thanks.
