### ISSUE TITLE
get_excerpt hook expects 2 arguments in WP 4.5 and above

### ISSUE THREAD

**Issue by eliot-akira** [eliot-akira/custom-content-shortcode#8]
https://wordpress.org/support/topic/compatibility-with-wp-450-get_the_excerpt-hook/

**Comment by Pross** [comment]
Please fix this issue as it causes fatal errors with any plugin that is using the filter the right way with two args.
The issue was originally reported nearly 2 years ago.
https://wordpress.org/support/topic/compatibility-with-wp-450-get_the_excerpt-hook/
https://wordpress.org/support/topic/excerpt-shortcode-compatibility-issue-with-beaver-builder-2-5-1/

**Comment by studioavanti** [comment]
Yes, please!

**Comment by CreativeManner** [comment]
Waiting on this for a while now.
